In [3]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\Aun Zaidi\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Aun Zaidi\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Aun Zaidi\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Aun Zaidi\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\Aun Zaidi\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Aun Zaidi\Downloads\brewbuzz_raw_orders.csv")
df.head()

,order_id,order_date,store_name,customer_id,customer_email,product_name,category,quantity,unit_price,promo_code,discount_percent,payment_method,order_total
0,197090,2025-06-07 04:26:04,BrewBuzz Uptown,8440,customer8440@example.com,Green Tea,Tea,1,-3.22,NaN,0.0,Cash,3.25
1,140550,2024-10-07 10:47:29,BrewBuzz Airport,8136,customer8136@example.com,Blueberry Muffin,Pastry,2,3.5,BOGO,50.0,App,3.50
2,136717,2025-06-11 23:33:43,BrewBuzz Riverside,14068,customer14068@example.com,Latte,Coffee,1,4.5,BOGO,0.0,Cash,4.50
3,100461,2025-10-17 11:50:16,BrewBuzz Riverside,9791,customer9791@example.com,Americano,Coffee,3,3.5,BOGO,50.0,Card,5.25
4,104866,2025-08-04 12:06:14,BrewBuzz Riverside,2656,customer2656@example.com,Croissant,Pastry,3,3.75,NaN,0.0,App,11.25

In [4]:
print(df.shape)

(100150, 13)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100150 entries, 0 to 100149
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   order_id          100150 non-null  int64
 1   order_date        99990 non-null   str
 2   store_name        100150 non-null  str
 3   customer_id       100150 non-null  int64
 4   customer_email    92188 non-null   str
 5   product_name      100150 non-null  str
 6   category          100150 non-null  str
 7   quantity          99932 non-null   str
 8   unit_price        99867 non-null   str
 9   promo_code        28724 non-null   str
 10  discount_percent  100150 non-null  float64
 11  payment_method    100150 non-null  str
 12  order_total       99717 non-null   float64
dtypes: float64(2), int64(2), str(9)
memory usage: 9.9 MB

In [6]:
df.describe()

            order_id    customer_id  discount_percent   order_total
count  100150.000000  100150.000000     100150.000000  99717.000000
mean   150001.222067    9980.265242          8.974039     11.511115
std     28866.431458    5766.949831         23.428678      9.868871
min    100001.000000       1.000000          0.000000      0.000000
25%    125004.250000    4989.000000          0.000000      4.750000
50%    150001.500000    9983.500000          0.000000      9.000000
75%    174997.750000   14942.000000          0.000000     14.000000
max    200000.000000   20000.000000        100.000000     51.960000

In [7]:
df.loc[0:2, ["store_name","customer_email","order_total"]]

           store_name             customer_email  order_total
0     BrewBuzz Uptown   customer8440@example.com         3.25
1    BrewBuzz Airport   customer8136@example.com         3.50
2  BrewBuzz Riverside  customer14068@example.com         4.50

In [8]:
df.iloc[0:3, 0:4]

   order_id           order_date          store_name  customer_id
0    197090  2025-06-07 04:26:04     BrewBuzz Uptown         8440
1    140550  2024-10-07 10:47:29    BrewBuzz Airport         8136
2    136717  2025-06-11 23:33:43  BrewBuzz Riverside        14068

In [10]:
members = df[(df["store_name"] == "BrewBuzz Airport") & (df["category"] == "Tea")]
print(len(members))

3278

In [11]:
members = df[(df["store_name"] == "BrewBuzz Airport") & (df["category"] == "Tea")]
print(members)

        order_id           order_date        store_name  customer_id  \
20        176865  2025-03-01 01:03:15  BrewBuzz Airport         7756
53        186708  2025-01-15 08:02:07  BrewBuzz Airport        17998
130       143608  2024-03-15 06:09:16  BrewBuzz Airport        13920
138       149175  2025-12-03 06:59:24  BrewBuzz Airport        10628
199       195854  2024-02-06 16:51:31  BrewBuzz Airport         3043
...          ...                  ...               ...          ...
99919     131812  2025-02-20 03:30:31  BrewBuzz Airport        17722
100062    185979  2024-07-12 12:23:34  BrewBuzz Airport         8864
100070    106445  2024-03-29 17:50:19  BrewBuzz Airport        15879
100071    170054  2025-07-27 05:00:46  BrewBuzz Airport         9239
100084    186058  2025-11-15 19:18:56  BrewBuzz Airport        12087

                   customer_email product_name category quantity unit_price  \
20       customer7756@example.com    Green Tea      Tea        2       3.25
53                            NaN    Green Tea      Tea        4       3.25
130     customer13920@example.com    Green Tea      Tea        3       3.25
138     customer10628@example.com   Chai Latte      Tea        2        4.0
199      customer3043@example.com    Green Tea      Tea        2       3.25
...                           ...          ...      ...      ...        ...
99919   customer17722@example.com   Chai Latte      Tea        1        4.0
100062   customer8864@example.com   Chai Latte      Tea        1        4.0
100070  customer15879@example.com   Chai Latte      Tea        3        4.0
100071   customer9239@example.com   Chai Latte      Tea        2        4.0
100084  customer12087@example.com    Green Tea      Tea        1       3.25

        promo_code  discount_percent payment_method  order_total
20             NaN               0.0           Cash         6.50
53             NaN               0.0            App        13.00
130            NaN               0.0           Cash         9.75
138            NaN               0.0            App          NaN
199            NaN               0.0            App         6.50
...            ...               ...            ...          ...
99919          NaN               0.0            App         4.00
100062  FREEPASTRY               0.0           Card         4.00
100070        BOGO              50.0           Cash         6.00
100071         NaN               0.0           Cash         8.00
100084         NaN               0.0            App         3.25

[3278 rows x 13 columns]

In [21]:
members_q = df.query('store_name == "Brewbuzz Airport" and category == "Tea"')
print(len(members_q))

0

In [19]:
df_new = df[["store_name", "order_total"]]
df_new.head()
print(len(df_new))
df_new.info()
df_new.describe()

100150
<class 'pandas.DataFrame'>
RangeIndex: 100150 entries, 0 to 100149
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   store_name   100150 non-null  str
 1   order_total  99717 non-null   float64
dtypes: float64(1), str(1)
memory usage: 1.5 MB

        order_total
count  99717.000000
mean      11.511115
std        9.868871
min        0.000000
25%        4.750000
50%        9.000000
75%       14.000000
max       51.960000

In [22]:
df.sort_values("order_total", ascending=False).head(5)[["store_name","customer_email","category"]]

                store_name             customer_email category
71649      BrewBuzz Uptown  customer11398@example.com    Merch
100147     BrewBuzz Uptown   customer3121@example.com    Merch
7       BrewBuzz Riverside  customer12342@example.com    Merch
71370      BrewBuzz Uptown   customer3279@example.com    Merch
52      BrewBuzz Riverside  customer13689@example.com    Merch

In [23]:
df['category'].value_counts()

category
Coffee    41827
Pastry    24848
Merch     16826
Tea       16649
Name: count, dtype: int64

In [24]:
df.groupby("store_name")["order_total"].sum()

store_name
  brewbuzz airport          1076.63
  brewbuzz downtown          977.00
  brewbuzz mall              957.09
  brewbuzz riverside         684.11
  brewbuzz uptown            774.86
BrewBuzz Airport          232191.17
BrewBuzz Downtown         225389.89
BrewBuzz Mall             230263.36
BrewBuzz Riverside        227928.61
BrewBuzz Uptown           227611.15
Name: order_total, dtype: float64